def seed_activites():
    """Seed the 172 activities from the Défi Santé specification."""
    from api import db
    from api.models import Activite

    if Activite.query.count() > 0:
        return  # Already seeded

    activites = [
        # (nom, description, points_homme, points_femme, points_mixte)
        ("Badminton", "Jeu de raquette en simple ou double", 3.6, 6.4, 8.0),
        ("Course / jogging", "Course à pied en plein air ou sur tapis", 4.8, 5.8, 6.4),
        ("Danse aérobie", "Cours de danse aérobique", 4.4, 4.8, 6.0),
        ("Elliptique (appareil)", "Entraînement sur appareil elliptique", 5.8, 6.4, 7.2),
        ("Escaliers", "Monter et descendre des escaliers", 4.8, 5.6, 6.4),
        ("Golf", "Golf sur parcours ou practice", 2.8, 3.2, 4.4),
        ("Hockey", "Hockey sur glace ou en salle", 7.2, 7.2, 7.2),
        ("Arts martiaux", "Karaté, judo, taekwondo, etc.", 6.4, 7.2, 8.8),
        ("Marche", "Marche à pied en plein air", 2.4, 3.6, 4.8),
        ("Zumba", "Cours de danse Zumba", 4.4, 4.8, 6.0),
        ("Natation", "Nage en piscine ou en eau libre", 6.0, 6.8, 7.6),
        ("Vélo extérieur", "Cyclisme en plein air", 5.2, 6.0, 6.8),
        ("Vélo stationnaire", "Entraînement sur vélo stationnaire", 5.0, 5.8, 6.6),
        ("Yoga", "Séance de yoga", 3.2, 3.6, 4.4),
        ("Pilates", "Cours de Pilates", 3.2, 3.6, 4.4),
        ("Musculation", "Entraînement avec poids et haltères", 5.6, 5.2, 6.0),
        ("CrossFit", "Entraînement CrossFit haute intensité", 7.6, 7.6, 7.6),
        ("Spinning", "Cours de vélo en salle (spinning)", 6.4, 6.8, 7.2),
        ("Squash", "Jeu de raquette en salle fermée", 7.2, 7.6, 8.0),
        ("Tennis", "Tennis simple ou double", 5.6, 6.4, 7.2),
        ("Tennis de table", "Ping-pong en simple ou double", 3.2, 3.6, 4.8),
        ("Volleyball", "Volleyball en salle ou plage", 4.8, 5.6, 6.4),
        ("Basketball", "Basketball en équipe", 6.4, 6.8, 7.2),
        ("Soccer", "Football soccer en équipe", 6.8, 7.2, 7.6),
        ("Football américain", "Football américain en équipe", 6.8, 6.8, 7.2),
        ("Baseball / softball", "Baseball ou softball en équipe", 4.4, 4.8, 5.6),
        ("Rugby", "Rugby à XV ou à 7", 7.2, 7.2, 7.6),
        ("Boxe", "Entraînement à la boxe", 7.2, 7.6, 8.0),
        ("Ski alpin", "Ski sur piste alpine", 6.0, 6.4, 7.2),
        ("Ski de fond", "Ski de fond en sentier", 6.8, 7.2, 8.0),
        ("Snowboard", "Snowboard sur piste", 5.6, 6.0, 6.8),
        ("Patin à glace", "Patinage sur glace", 5.6, 6.0, 6.8),
        ("Patin à roues alignées", "Rollerblading en plein air", 5.2, 5.6, 6.4),
        ("Planche à roulettes", "Skateboard en plein air", 4.0, 4.4, 5.2),
        ("Randonnée pédestre", "Randonnée en nature avec dénivelé", 4.8, 5.6, 6.4),
        ("Randonnée en raquettes", "Raquettes à neige en hiver", 5.6, 6.0, 6.8),
        ("Kayak / canot", "Kayak ou canot sur l'eau", 5.6, 6.0, 6.8),
        ("Planche à voile / kitesurf", "Sports nautiques de glisse", 6.4, 6.8, 7.2),
        ("Surf", "Surf sur les vagues", 6.0, 6.4, 7.0),
        ("Plongée sous-marine", "Plongée avec équipement", 5.2, 5.6, 6.4),
        ("Escalade", "Escalade en salle ou en falaise", 6.4, 7.0, 7.6),
        ("Trampoline", "Sauts sur trampoline", 5.6, 6.0, 6.8),
        ("Gymnastics", "Gymnastique artistique ou rythmique", 5.6, 6.0, 6.8),
        ("Cheerleading", "Cheerleading en équipe", 4.8, 5.2, 6.0),
        ("Danse contemporaine", "Danse contemporaine ou moderne", 4.8, 5.2, 6.4),
        ("Danse classique (ballet)", "Cours de ballet classique", 4.4, 4.8, 5.6),
        ("Danse hip-hop", "Cours de danse hip-hop", 5.2, 5.6, 6.4),
        ("Danse latine", "Salsa, merengue, bachata, etc.", 4.4, 4.8, 5.6),
        ("Aquagym", "Gymnasique aquatique en piscine", 4.0, 4.4, 5.2),
        ("Plongeon", "Plongeon en piscine", 5.2, 5.6, 6.4),
        ("Water-polo", "Water-polo en piscine", 6.8, 7.2, 7.6),
        ("Aviron", "Aviron en lac ou rivière", 7.2, 7.6, 8.0),
        ("Course d'obstacles", "Course Spartan, Tough Mudder, etc.", 7.6, 7.6, 8.0),
        ("Triathlon", "Triathlon toutes distances", 8.0, 8.0, 8.0),
        ("Ironman", "Triathlon longue distance (Ironman)", 8.8, 8.8, 8.8),
        ("Marathon", "Course marathon 42,2 km", 8.0, 8.0, 8.0),
        ("Demi-marathon", "Course demi-marathon 21,1 km", 7.2, 7.2, 7.2),
        ("5 km / 10 km", "Course de 5 km ou 10 km", 5.6, 5.6, 5.6),
        ("Marche rapide", "Marche à allure soutenue", 3.2, 4.4, 5.2),
        ("Marche nordique", "Marche nordique avec bâtons", 4.0, 5.0, 5.8),
        ("Tir à l'arc", "Tir à l'arc en salle ou extérieur", 2.0, 2.4, 3.2),
        ("Escrime", "Escrime en salle", 4.8, 5.2, 6.0),
        ("Lutte", "Lutte gréco-romaine ou libre", 6.4, 6.8, 7.6),
        ("Jiu-jitsu brésilien", "BJJ en salle", 6.8, 7.2, 8.0),
        ("MMA", "Arts martiaux mixtes", 7.6, 7.6, 8.0),
        ("Kickboxing", "Cours de kickboxing", 7.2, 7.6, 8.0),
        ("Muay thaï", "Boxe thaïlandaise", 7.2, 7.6, 8.0),
        ("Tai chi", "Tai chi chuan", 2.4, 2.8, 3.2),
        ("Qi gong", "Exercices de qi gong", 2.0, 2.4, 3.0),
        ("Stretching / flexibilité", "Exercices d'étirement et de flexibilité", 1.6, 2.0, 2.4),
        ("HIIT", "Entraînement par intervalles de haute intensité", 7.6, 7.6, 7.6),
        ("Tabata", "Entraînement Tabata (20s/10s)", 7.2, 7.2, 7.2),
        ("Circuit training", "Entraînement en circuit", 6.4, 6.8, 7.2),
        ("Bootcamp", "Cours de bootcamp militaire", 7.2, 7.2, 7.2),
        ("Aérobic step", "Cours d'aérobic avec step", 5.2, 5.6, 6.4),
        ("Zumba Gold", "Zumba adaptée pour seniors", 3.2, 3.6, 4.4),
        ("Yoga hot (Bikram)", "Yoga en salle chauffée", 4.0, 4.4, 5.2),
        ("Yoga power / vinyasa", "Yoga dynamique et fluide", 4.0, 4.4, 5.2),
        ("Barre fitness", "Cours de barre inspiré du ballet", 3.6, 4.0, 4.8),
        ("TRX / suspension", "Entraînement en suspension TRX", 6.0, 6.4, 7.0),
        ("Calisthenics", "Exercices au poids du corps (dips, tractions)", 5.6, 6.0, 6.8),
        ("Jump rope / corde à sauter", "Entraînement à la corde à sauter", 6.4, 6.8, 7.2),
        ("Hula hoop", "Exercices avec hula hoop", 3.2, 3.6, 4.4),
        ("Badminton (compétition)", "Badminton en compétition officielle", 4.8, 7.2, 9.0),
        ("Quilles / bowling", "Bowling en salle", 1.6, 2.0, 2.8),
        ("Billard / snooker", "Billard en salle", 1.2, 1.6, 2.0),
        ("Fléchettes", "Fléchettes en salle", 1.2, 1.6, 2.0),
        ("Pétanque / bocce", "Pétanque en plein air", 1.6, 2.0, 2.8),
        ("Croquet", "Croquet sur gazon", 1.6, 2.0, 2.8),
        ("Disc golf", "Golf avec disque volant", 2.4, 2.8, 3.6),
        ("Ultimate frisbee", "Frisbee ultime en équipe", 6.0, 6.4, 7.2),
        ("Football australien", "Football australien en équipe", 6.8, 6.8, 7.2),
        ("Handball", "Handball en salle", 6.4, 6.8, 7.2),
        ("Cricket", "Cricket en équipe", 4.0, 4.4, 5.2),
        ("Lacrosse", "Lacrosse en équipe", 6.4, 6.8, 7.2),
        ("Polo", "Polo à cheval", 4.4, 4.8, 5.6),
        ("Équitation", "Équitation en manège ou en nature", 3.6, 4.0, 4.8),
        ("Natation synchronisée", "Natation synchronisée en équipe", 5.6, 6.0, 6.8),
        ("Water polo (comp)", "Water polo en compétition", 7.6, 8.0, 8.4),
        ("Boxe anglaise (comp)", "Boxe en compétition officielle", 8.0, 8.4, 8.8),
        ("Longue randonnée", "Randonnée de plus de 4h", 6.4, 7.2, 8.0),
        ("Camping actif", "Activités physiques en camping", 3.2, 3.6, 4.4),
        ("Jardinage intensif", "Jardinage avec activité physique importante", 2.8, 3.2, 4.0),
        ("Déménagement / travaux physiques", "Déménagement ou travaux physiques intenses", 4.4, 4.8, 5.6),
        ("Danse de salon", "Danse de salon (valse, tango, etc.)", 3.6, 4.0, 4.8),
        ("Flamenco", "Danse flamenco", 4.4, 4.8, 5.6),
        ("Danse orientale", "Danse du ventre", 3.6, 4.0, 4.8),
        ("Activité physique professionnelle", "Travail physiquement exigeant (construction, etc.)", 4.0, 4.0, 4.0),
        ("Nettoyage intensif", "Nettoyage maison avec activité physique", 2.0, 2.4, 3.0),
        ("Coupe de bois", "Coupe et fendage du bois", 5.6, 5.6, 5.6),
        ("Raquetball", "Raquetball en salle", 6.4, 6.8, 7.6),
        ("Pelote basque", "Pelote basque ou fronton", 6.0, 6.4, 7.2),
        ("Padel", "Padel tennis en salle ou extérieur", 5.6, 6.0, 6.8),
        ("Pickleball", "Pickleball en salle ou extérieur", 4.0, 4.4, 5.2),
        ("Bocce ball", "Bocce ball en plein air", 1.6, 2.0, 2.8),
        ("Tir sportif", "Tir sportif en stand", 1.6, 2.0, 2.8),
        ("Tir à la carabine", "Tir à la carabine en stand", 1.6, 2.0, 2.8),
        ("Pentathlon moderne", "Pentathlon (natation, équitation, escrime, etc.)", 8.0, 8.0, 8.0),
        ("Décathlon", "Décathlon (10 épreuves d'athlétisme)", 8.0, 8.0, 8.0),
        ("Lancer du poids / javelot", "Athlétisme lancer", 4.0, 4.4, 5.2),
        ("Saut en hauteur / longueur", "Athlétisme saut", 4.8, 5.2, 6.0),
        ("Sprint / vitesse", "Course de vitesse (100m, 200m)", 7.2, 7.2, 7.2),
        ("Course de haies", "Course athlétisme avec haies", 7.2, 7.2, 7.2),
        ("Marche athlétique", "Marche athlétique en compétition", 5.2, 5.6, 6.4),
        ("Judo (compétition)", "Judo en compétition officielle", 7.6, 8.0, 8.4),
        ("Karaté (compétition)", "Karaté en compétition officielle", 7.2, 7.6, 8.0),
        ("Taekwondo (compétition)", "Taekwondo en compétition officielle", 7.6, 8.0, 8.4),
        ("Sambo", "Sambo russe (lutte et combat)", 7.2, 7.2, 7.6),
        ("Sumo", "Sumo traditionnel", 5.6, 5.6, 6.0),
        ("Capoeira", "Capoeira brésilienne", 6.0, 6.4, 7.2),
        ("Krav maga", "Krav maga autodéfense", 7.2, 7.2, 7.6),
        ("Wing chun / kung fu", "Kung fu ou wing chun", 6.0, 6.4, 7.2),
        ("Canoë-kayak (compétition)", "Canoë-kayak en compétition", 8.0, 8.0, 8.4),
        ("Voile / navigation", "Voile sur lac ou mer", 3.6, 4.0, 4.8),
        ("Kitesurf (débutant)", "Kitesurf en apprentissage", 4.8, 5.2, 6.0),
        ("Stand-up paddle", "Stand-up paddleboard sur l'eau", 4.8, 5.2, 6.0),
        ("Wake-board / ski nautique", "Sports nautiques tractés", 6.0, 6.4, 7.2),
        ("Plongée en apnée", "Apnée et snorkeling", 4.0, 4.4, 5.2),
        ("Vélo de montagne", "VTT sur sentiers", 6.4, 7.0, 7.6),
        ("Cyclocross", "Cyclocross sur terrain varié", 7.2, 7.6, 8.0),
        ("Vélo BMX", "BMX freestyle ou racing", 5.6, 6.0, 6.8),
        ("Vélo cargo", "Vélo avec charge lourde", 4.4, 4.8, 5.6),
        ("Trottinette électrique (non-motorisé)", "Trottinette à propulsion humaine", 3.2, 3.6, 4.4),
        ("Biathlon", "Biathlon (ski de fond + tir)", 7.6, 7.6, 8.0),
        ("Curling", "Curling sur glace", 2.8, 3.2, 4.0),
        ("Patinage artistique", "Patinage artistique sur glace", 6.0, 6.4, 7.2),
        ("Patinage de vitesse", "Patinage de vitesse sur glace", 7.2, 7.6, 8.0),
        ("Luge / bobsleigh", "Luge ou bobsleigh en piste", 4.0, 4.4, 5.2),
        ("Motoneige (randonnée)", "Randonnée en motoneige (pilotage)", 2.4, 2.8, 3.6),
        ("Ski acrobatique", "Ski avec sauts et figures", 6.8, 7.2, 7.6),
        ("Snowkite", "Cerf-volant traction sur neige", 6.4, 6.8, 7.6),
        ("Roller derby", "Roller derby en équipe", 6.8, 7.2, 7.6),
        ("Longe-côte", "Marche en mer (longe-côte)", 4.8, 5.6, 6.4),
        ("Beach volley", "Volleyball de plage", 6.0, 6.4, 7.2),
        ("Beach soccer", "Soccer sur plage", 7.2, 7.6, 8.0),
        ("Parkoure / free running", "Parkour en milieu urbain", 7.2, 7.2, 7.6),
        ("Pole dance (fitness)", "Pole dance pour la condition physique", 5.2, 5.6, 6.4),
        ("Aerial yoga", "Yoga aérien avec hamac", 4.4, 4.8, 5.6),
        ("Fitness fonctionnel", "Entraînement fonctionnel (kettlebell, etc.)", 6.4, 6.8, 7.2),
        ("Plyométrie", "Entraînement plyométrique (box jumps, etc.)", 7.2, 7.2, 7.6),
        ("Stretching actif", "Stretching dynamique et actif", 2.0, 2.4, 3.0),
        ("Foam rolling / récupération", "Récupération active avec rouleau", 1.2, 1.6, 2.0),
        ("Méditation active (walking meditation)", "Méditation en marchant", 1.6, 2.0, 2.4),
        ("Aqua jogging", "Course en piscine avec ceinture", 5.2, 5.6, 6.4),
        ("Volley assis", "Volleyball adapté en position assise", 3.6, 4.0, 4.8),
        ("Bocce adapté", "Pétanque adaptée pour personnes à mobilité réduite", 1.2, 1.6, 2.0),
        ("Danse en fauteuil", "Danse adaptée en fauteuil roulant", 2.4, 2.8, 3.6),
        ("Para-athlétisme", "Athlétisme adapté", 5.6, 6.0, 6.4),
    ]

    for nom, desc, ph, pf, pm in activites:
        a = Activite(
            nom=nom,
            description=desc,
            points_homme=ph,
            points_femme=pf,
            points_mixte=pm,
        )
        db.session.add(a)

    try:
        db.session.commit()
        print(f"✅ {len(activites)} activités ajoutées.")
    except Exception as e:
        db.session.rollback()
        print(f"⚠️ Seed activities error: {e}")
